project:
  type: book

book:
  title: "Classical Language Arts: Literature Companion"
  author: "Christian Bolander"
  date: "6/13/2026"
  chapters:
    - index.qmd

    - part: "Introduction"
      chapters:
        - introduction/using.qmd
        - introduction/rhythm.qmd

    - part: "Literature Units"
      chapters:
        - units/aesop.qmd
        - units/alice.qmd
        - units/treasure-island.qmd
        - units/little-women.qmd
        - units/the-secret-garden.qmd
        - units/the-wind-in-the-willows.qmd

    - part: "Planning"
      chapters:
        - student-dashboard.qmd
        - google-docs-workflow.qmd
        - student-response-template.qmd
        - planning.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: book
  epub: default
